from django.contrib import admin

# Register your models here.
from . import models
admin.site.register(models.Produit)
admin.site.register(models.Category)
admin.site.register(models.Coupon)
# register all models in the admin site
admin.site.register(models.Pairingcode)
admin.site.register(models.Shippingfees)
admin.site.register(models.Mark)
admin.site.register(models.Client)
admin.site.register(models.Order)
admin.site.register(models.Orderitem)
admin.site.register(models.Bonlivraison)
admin.site.register(models.Facture)
admin.site.register(models.Livraisonitem)
admin.site.register(models.Supplier)
admin.site.register(models.Outfacture)
admin.site.register(models.Carlogos)
admin.site.register(models.Itemsbysupplier)
admin.site.register(models.PaymentSupplier)
admin.site.register(models.PaymentClientbl)
admin.site.register(models.PaymentClientfc)
admin.site.register(models.Ordersnotif)
admin.site.register(models.Connectedusers)
admin.site.register(models.Avoirclient)
admin.site.register(models.Stockin)
admin.site.register(models.Promotion)
admin.site.register(models.UserSession)
admin.site.register(models.Refstats)
admin.site.register(models.Cart)
admin.site.register(models.Cartitems)
admin.site.register(models.Represent)
admin.site.register(models.wishlist)
admin.site.register(models.Wich)
admin.site.register(models.Notification)
admin.site.register(models.Modifierstock)
admin.site.register(models.Notesrepresentant)
admin.site.register(models.Avoirsupplier)
admin.site.register(models.Achathistory)
admin.site.register(models.Repcartitem)
admin.site.register(models.Repcart)
admin.site.register(models.Excelecheances)
admin.site.register(models.Bonsortie)
admin.site.register(models.Sortieitem)
admin.site.register(models.Devi)
admin.site.register(models.DeviItem)
admin.site.register(models.Avanceclient)
admin.site.register(models.Factureachat)
admin.site.register(models.Outfactureachat)
admin.site.register(models.Avancesupplier)
admin.site.register(models.CommandItemsupplier)
admin.site.register(models.Commandsupplier)
admin.site.register(models.Config)
admin.site.register(models.Notavailable)
admin.site.register(models.Caisse)
admin.site.register(models.Bank)
admin.site.register(models.Transfer)
# admin.site.register(models.Notavailable)
# admin.site.register(models.Notavailable)
# admin.site.register(models.Notavailable)
# admin.site.register(models.Notavailable)
# admin.site.register(models.Notavailable)
# admin.site.register(models.Notavailable)
# admin.site.register(models.Notavailable)
# admin.site.register(models.Notavailable)
# admin.site.register(models.Notavailable)
